[package]
name = "pirate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

macros = []


[dependencies]
serde = {version="1.0.144", features = ["derive"]}
serde-pickle = "1.1.1"
tokio = {version = "1.21.1", features = ["net", "io-util", "rt", "macros"]}
async-trait = "0.1.57"
pirate_macro_lib = { path = "pirate-macro-lib"}